const LESETEXTE = [
  {
    bereich: "Lies und male",
    nummer: 1,
    titel: "Haus mit Garten",
    level: "mittel",
    text: "Oben links am Himmel scheint eine Sonne. In der Mitte steht ein Haus. Das Haus hat eine rote Tür und zwei Fenster. Vor dem Haus ist ein Garten mit vielen bunten Blumen. Rechts neben dem Haus steht ein großer Baum. Unter dem Baum sitzt eine Katze. Links neben dem Haus steht ein Fahrrad.",
    aufgaben: ["Male das Bild genau nach dem Text.", "Lies Satz für Satz.", "Kontrolliere am Ende dein Bild."],
    fragen: ["Wo ist die Sonne?", "Was steht in der Mitte?", "Was sitzt unter dem Baum?"],
    lesetipps: ["Lies jeden Satz zweimal.", "Male erst, wenn du den Satz verstanden hast.", "Kontrolliere dein Bild mit dem Text."],
    toniTipp: "Male nur Dinge, die im Text stehen."
  },
  {
    bereich: "Lies und male",
    nummer: 2,
    titel: "Spielplatz",
    level: "mittel",
    text: "In der Mitte steht eine große Schaukel. Auf der Schaukel sitzt ein Kind mit einer blauen Mütze. Rechts davon steht eine rote Rutsche. Links im Bild liegt ein gelber Ball im Sand. Hinter der Schaukel wächst ein kleiner Baum. Oben rechts fliegt ein Vogel.",
    aufgaben: ["Male den Spielplatz nach dem Text.", "Achte genau auf links und rechts.", "Kontrolliere die Farben."],
    fragen: ["Wo liegt der Ball?", "Welche Farbe hat die Rutsche?", "Wer fliegt oben rechts?"],
    lesetipps: ["Achte auf die Wörter links und rechts.", "Lies die Farbwörter genau.", "Prüfe die Reihenfolge."],
    toniTipp: "Bei Malaufgaben sind kleine Wörter sehr wichtig."
  },
  {
    bereich: "Lies und male",
    nummer: 3,
    titel: "Am Meer",
    level: "mittel",
    text: "Unten im Bild ist ein breiter Strand. Auf dem Strand steht ein grüner Eimer. Neben dem Eimer liegt eine gelbe Schaufel. Im Meer schwimmt ein kleines Boot. Am Himmel fliegen drei Möwen. Oben links scheint die Sonne. Rechts am Wasser liegt eine Muschel.",
    aufgaben: ["Male Strand und Meer.", "Male alle Dinge an den richtigen Platz.", "Zähle die Möwen."],
    fragen: ["Was steht auf dem Strand?", "Wie viele Möwen fliegen am Himmel?", "Wo liegt die Muschel?"],
    lesetipps: ["Lies langsam.", "Suche zuerst die Ortswörter.", "Kontrolliere die Anzahl."],
    toniTipp: "Zahlen im Text musst du genau beachten."
  },
  {
    bereich: "Lies und male",
    nummer: 4,
    titel: "Im Klassenzimmer",
    level: "mittel",
    text: "Vorne im Raum hängt eine grüne Tafel. Vor der Tafel steht ein Tisch. Auf dem Tisch liegt ein rotes Buch. Rechts neben dem Tisch steht ein Stuhl. Links an der Wand ist ein Fenster. Unter dem Fenster steht eine Pflanze. Auf dem Boden liegt ein blauer Ranzen.",
    aufgaben: ["Male das Klassenzimmer nach dem Text.", "Achte auf vorne, rechts, links und unter.", "Kontrolliere die Farben."],
    fragen: ["Was liegt auf dem Tisch?", "Wo steht die Pflanze?", "Welche Farbe hat der Ranzen?"],
    lesetipps: ["Achte auf Ortswörter.", "Lies Satz für Satz.", "Male nicht zu schnell."],
    toniTipp: "Genaue Leser achten auf jedes kleine Wort."
  },
  {
    bereich: "Lies und male",
    nummer: 5,
    titel: "Geburtstag",
    level: "mittel",
    text: "Auf dem Tisch steht ein großer Kuchen mit fünf Kerzen. Neben dem Kuchen liegt ein Geschenk mit einer Schleife. Toni sitzt vor dem Tisch und freut sich. Rechts neben Toni steht ein Kind mit einem Luftballon. Oben hängen drei bunte Girlanden. Unter dem Tisch schläft ein kleiner Hund.",
    aufgaben: ["Male die Geburtstagsszene.", "Achte auf die Anzahl der Kerzen und Girlanden.", "Male Toni fröhlich."],
    fragen: ["Wie viele Kerzen hat der Kuchen?", "Was liegt neben dem Kuchen?", "Wer schläft unter dem Tisch?"],
    lesetipps: ["Lies Zahlen besonders genau.", "Achte auf neben, vor und unter.", "Kontrolliere dein Bild."],
    toniTipp: "Wenn du genau malst, hast du genau gelesen."
  },
  {
    bereich: "Lies und male",
    nummer: 6,
    titel: "Im Wald",
    level: "schwer",
    text: "In der Mitte steht ein hoher Baum mit vielen Blättern. Links neben dem Baum wächst ein roter Pilz. Rechts hinter dem Baum schaut ein kleiner Fuchs hervor. Auf einem Ast sitzt ein Vogel. Unten im Gras krabbelt ein Käfer. Toni steht vor dem Baum und hält einen Korb.",
    aufgaben: ["Male den Wald genau nach dem Text.", "Achte auf vor, hinter, links und rechts.", "Male alle Tiere."],
    fragen: ["Wer schaut hinter dem Baum hervor?", "Was hält Toni?", "Wo sitzt der Vogel?"],
    lesetipps: ["Lies den Text zweimal.", "Markiere im Kopf die Ortswörter.", "Kontrolliere alle Tiere."],
    toniTipp: "Ortswörter helfen dir beim Verstehen."
  },
  {
    bereich: "Lies und male",
    nummer: 7,
    titel: "In Tonis Zimmer",
    level: "schwer",
    text: "Links im Zimmer steht ein Bett mit einer blauen Decke. Neben dem Bett liegt ein rundes Kissen. In der Mitte steht ein kleiner Tisch. Auf dem Tisch liegt ein Buch. Rechts an der Wand steht ein Regal mit drei Büchern. Unter dem Regal liegt ein Teddy. Am Fenster hängt ein gelber Vorhang.",
    aufgaben: ["Male Tonis Zimmer.", "Achte auf die Farben.", "Male genau drei Bücher ins Regal."],
    fragen: ["Welche Farbe hat die Decke?", "Was liegt unter dem Regal?", "Wo liegt das Buch?"],
    lesetipps: ["Lies nicht zu schnell.", "Achte auf Zahlen und Farben.", "Kontrolliere dein Bild Satz für Satz."],
    toniTipp: "Ein gutes Bild zeigt, dass du den Text verstanden hast."
  },
  {
    bereich: "Lies und male",
    nummer: 8,
    titel: "Auf dem Bauernhof",
    level: "schwer",
    text: "Vor dem Stall steht eine braune Kuh. Rechts neben der Kuh steht ein kleines Kalb. Links vom Stall pickt ein Huhn Körner. Hinter dem Zaun steht ein Pferd. Oben auf dem Dach sitzt eine Katze. Toni hält eine Schüssel mit Futter in der Hand.",
    aufgaben: ["Male den Bauernhof.", "Achte darauf, wo die Tiere stehen.", "Male Toni mit der Futterschüssel."],
    fragen: ["Wer steht hinter dem Zaun?", "Was macht das Huhn?", "Was hält Toni in der Hand?"],
    lesetipps: ["Suche zuerst alle Tiere.", "Achte auf vor, hinter, links und rechts.", "Lies die Sätze mit Toni noch einmal."],
    toniTipp: "Bei vielen Tieren hilft langsames Lesen."
  },
  {
    bereich: "Lies und male",
    nummer: 9,
    titel: "Beim Picknick",
    level: "schwer",
    text: "Auf einer grünen Wiese liegt eine rote Decke. Auf der Decke stehen ein Korb, zwei Becher und ein Teller mit Brot. Links neben der Decke sitzt Toni. Rechts neben der Decke sitzt ein Kind. Hinter den beiden wächst ein Apfelbaum. Unter dem Baum liegt ein Ball.",
    aufgaben: ["Male das Picknick.", "Male alle Dinge auf der Decke.", "Achte auf links, rechts und hinter."],
    fragen: ["Was steht auf der Decke?", "Wer sitzt links neben der Decke?", "Was liegt unter dem Baum?"],
    lesetipps: ["Lies die Aufzählung langsam.", "Kontrolliere die Anzahl der Becher.", "Prüfe dein Bild am Schluss."],
    toniTipp: "Bei Aufzählungen musst du besonders genau lesen."
  },
  {
    bereich: "Lies und male",
    nummer: 10,
    titel: "In der Höhle",
    level: "schwer",
    text: "Toni sitzt in einer gemütlichen Höhle aus Decken. Links neben Toni liegt ein Kissen. Rechts neben Toni steht eine kleine Lampe. Vor Toni liegt ein Buch auf dem Boden. Hinter Toni hängt eine Lichterkette. Am Eingang der Höhle sitzt ein Teddy.",
    aufgaben: ["Male die Höhle.", "Achte auf alle Ortsangaben.", "Male die Höhle gemütlich."],
    fragen: ["Woraus ist die Höhle gebaut?", "Was steht rechts neben Toni?", "Wo sitzt der Teddy?"],
    lesetipps: ["Lies den Text zweimal.", "Suche die Wörter links, rechts, vor und hinter.", "Kontrolliere am Ende jedes Detail."],
    toniTipp: "Starke Leser lesen genau und prüfen noch einmal."
  },
  {
    bereich: "Lesedetektiv",
    nummer: 1,
    titel: "Toni auf dem Spielplatz",
    level: "mittel",
    text: "Toni geht mit Lina auf den Spielplatz. Zuerst rutscht Lina die rote Rutsche hinunter. Toni schaukelt hoch in die Luft. Danach spielen beide mit einem gelben Ball. Plötzlich rollt der Ball unter die Bank. Toni krabbelt darunter und findet ihn wieder. Lina lacht laut.",
    aufgaben: ["Suche drei Nomen.", "Finde zwei Verben.", "Finde ein Adjektiv.", "Finde ein Wort mit sch.", "Schreibe einen Satz aus dem Text ordentlich ab."],
    fragen: ["Mit wem geht Toni auf den Spielplatz?", "Wohin rollt der Ball?", "Wer findet den Ball?"],
    lesetipps: ["Lies mit dem Finger.", "Suche erst die Namenwörter.", "Lies den Text danach noch einmal."],
    toniTipp: "Nomen kannst du oft anfassen oder sehen."
  },
  {
    bereich: "Lesedetektiv",
    nummer: 2,
    titel: "Das verschwundene Pausenbrot",
    level: "mittel",
    text: "Toni hat Hunger. In seiner Tasche sucht er sein Pausenbrot. Doch die Dose ist leer. Toni schaut unter den Tisch und neben den Stuhl. Da sieht er eine kleine Maus. Die Maus sitzt hinter dem Ranzen. Neben ihr liegt ein Stück Brot. Toni muss lachen.",
    aufgaben: ["Suche zwei Wörter mit au.", "Finde drei Nomen.", "Finde zwei Verben.", "Finde ein Wort mit sch.", "Schreibe das längste Wort ab."],
    fragen: ["Was sucht Toni?", "Wo sitzt die Maus?", "Warum muss Toni lachen?"],
    lesetipps: ["Lies langsam.", "Kreise im Kopf wichtige Wörter ein.", "Lies schwierige Wörter zweimal."],
    toniTipp: "Detektive lesen besonders genau."
  },
  {
    bereich: "Lesedetektiv",
    nummer: 3,
    titel: "Besuch im Zoo",
    level: "mittel",
    text: "Toni besucht mit seiner Klasse den Zoo. Zuerst sehen die Kinder die Affen. Ein Affe klettert schnell auf einen Ast. Danach gehen alle zu den Elefanten. Der große Elefant frisst einen Apfel. Am Ende schaut Toni lange zu den Pinguinen. Er findet sie besonders lustig.",
    aufgaben: ["Suche drei Tiernamen.", "Finde zwei Verben.", "Finde zwei Adjektive.", "Finde ein Wort mit ff.", "Schreibe einen Tiernamen ordentlich ab."],
    fragen: ["Wohin geht Toni mit der Klasse?", "Was frisst der Elefant?", "Welche Tiere findet Toni lustig?"],
    lesetipps: ["Suche zuerst die Tiere.", "Lies die Sätze mit den Tieren noch einmal.", "Achte auf Wörter, die beschreiben."],
    toniTipp: "Adjektive sagen, wie etwas ist."
  },
  {
    bereich: "Lesedetektiv",
    nummer: 4,
    titel: "Ein Regentag",
    level: "mittel",
    text: "Draußen regnet es stark. Toni sitzt am Fenster und hört den Regen. Dicke Tropfen laufen an der Scheibe hinunter. Auf der Straße springt ein Kind in eine Pfütze. Toni holt sein Buch und liest auf dem Sofa. Später malt er einen bunten Regenbogen.",
    aufgaben: ["Suche zwei Wörter mit ei.", "Finde drei Nomen.", "Finde zwei Verben.", "Finde ein Adjektiv.", "Finde ein Wort mit sch."],
    fragen: ["Wo sitzt Toni?", "Was macht das Kind auf der Straße?", "Was malt Toni später?"],
    lesetipps: ["Lies Satz für Satz.", "Achte auf Tun und Dinge.", "Suche Farbwörter."],
    toniTipp: "Manche Antworten stehen genau im Text."
  },
  {
    bereich: "Lesedetektiv",
    nummer: 5,
    titel: "Toni und der Hund",
    level: "schwer",
    text: "Auf dem Schulhof hört Toni ein leises Winseln. Neben der Hecke sitzt ein kleiner Hund. Er hat eine rote Leine um den Hals. Toni geht vorsichtig zu ihm. Der Hund zittert, aber er läuft nicht weg. Lina holt die Lehrerin. Gemeinsam finden sie den Besitzer.",
    aufgaben: ["Suche vier Nomen.", "Finde drei Verben.", "Finde zwei Adjektive.", "Finde ein Wort mit sch.", "Finde ein zusammengesetztes Wort."],
    fragen: ["Wo sitzt der Hund?", "Wer holt die Lehrerin?", "Wie fühlt sich der Hund?"],
    lesetipps: ["Lies den Text zweimal.", "Achte auf Gefühle.", "Suche lange Wörter."],
    toniTipp: "Zusammengesetzte Wörter bestehen aus zwei Wörtern."
  },
  {
    bereich: "Lesedetektiv",
    nummer: 6,
    titel: "Im Garten",
    level: "schwer",
    text: "Im Garten blühen viele Blumen. Toni gießt die gelben Tulpen mit einer kleinen Kanne. Neben dem Beet krabbelt ein Marienkäfer über ein Blatt. Eine Biene summt leise. Plötzlich entdeckt Toni eine reife Erdbeere. Er pflückt sie und legt sie vorsichtig in den Korb.",
    aufgaben: ["Suche drei Pflanzenwörter.", "Finde drei Verben.", "Finde zwei Adjektive.", "Finde ein Wort mit ie.", "Finde ein Wort mit ä."],
    fragen: ["Was gießt Toni?", "Welches Tier krabbelt über ein Blatt?", "Was legt Toni in den Korb?"],
    lesetipps: ["Suche erst die Gartenwörter.", "Lies Wörter mit ie besonders genau.", "Kontrolliere deine Antworten im Text."],
    toniTipp: "Der Text verrät dir mehr, wenn du langsam liest."
  },
  {
    bereich: "Lesedetektiv",
    nummer: 7,
    titel: "Ein Ausflug ans Meer",
    level: "schwer",
    text: "Toni fährt mit seiner Familie ans Meer. Am Strand zieht er die Schuhe aus. Der Sand ist warm und weich. Neben einer Muschel findet Toni einen kleinen Seestern. Im Wasser schwimmt ein rotes Boot. Plötzlich ruft Papa: „Kommt zum Picknick!“ Toni rennt schnell zurück.",
    aufgaben: ["Suche vier Nomen.", "Finde drei Verben.", "Finde zwei Adjektive.", "Finde ein Wort mit ee.", "Finde ein Wort mit sch."],
    fragen: ["Wohin fährt Toni?", "Was findet Toni neben der Muschel?", "Wer ruft zum Picknick?"],
    lesetipps: ["Lies die Strandwörter genau.", "Achte auf Farben.", "Suche Wörter mit besonderen Buchstaben."],
    toniTipp: "Auch kleine Wörter sind wichtig."
  },
  {
    bereich: "Lesedetektiv",
    nummer: 8,
    titel: "Toni hat Geburtstag",
    level: "schwer",
    text: "Heute hat Toni Geburtstag. Auf dem Tisch steht ein Kuchen mit sechs Kerzen. Mama stellt eine Schüssel mit Erdbeeren daneben. Toni bekommt ein kleines Paket. Darin liegt ein grüner Ball. Seine Freunde singen ein Lied. Danach spielen alle zusammen im Garten.",
    aufgaben: ["Suche vier Nomen.", "Finde drei Verben.", "Finde zwei Adjektive.", "Finde ein Wort mit ch.", "Finde ein Wort mit ng."],
    fragen: ["Wie viele Kerzen hat der Kuchen?", "Was liegt im Paket?", "Wo spielen die Freunde danach?"],
    lesetipps: ["Achte auf Zahlen.", "Suche erst die Dinge.", "Lies das Ende noch einmal."],
    toniTipp: "Zahlen sind wichtige Textstellen."
  },
  {
    bereich: "Lesedetektiv",
    nummer: 9,
    titel: "Die geheimnisvolle Kiste",
    level: "schwer",
    text: "Unter der Treppe findet Toni eine alte Kiste. Sie ist schwer und staubig. Auf dem Deckel klebt ein gelber Stern. Toni öffnet die Kiste vorsichtig. Darin liegen ein Schlüssel, eine Karte und ein kleiner Stein. Plötzlich hört Toni ein leises Klopfen.",
    aufgaben: ["Suche fünf Nomen.", "Finde drei Verben.", "Finde zwei Adjektive.", "Finde ein Wort mit st.", "Finde ein Wort mit ei."],
    fragen: ["Wo findet Toni die Kiste?", "Was klebt auf dem Deckel?", "Was hört Toni plötzlich?"],
    lesetipps: ["Lies geheimnisvolle Stellen langsam.", "Achte auf Dinge in der Kiste.", "Lies den letzten Satz zweimal."],
    toniTipp: "Der letzte Satz macht neugierig."
  },
  {
    bereich: "Lesedetektiv",
    nummer: 10,
    titel: "Im Wald",
    level: "schwer",
    text: "Toni geht am Nachmittag in den Wald. Zwischen den hohen Bäumen ist es kühl. Auf dem Boden liegen Blätter, Zweige und ein Tannenzapfen. Plötzlich raschelt es im Gebüsch. Toni bleibt stehen und lauscht. Ein kleiner Fuchs schaut heraus. Dann verschwindet er leise zwischen den Bäumen.",
    aufgaben: ["Suche fünf Nomen.", "Finde drei Verben.", "Finde zwei Adjektive.", "Finde ein Wort mit sch.", "Finde ein Wort mit äu."],
    fragen: ["Wann geht Toni in den Wald?", "Was raschelt im Gebüsch?", "Welches Tier schaut heraus?"],
    lesetipps: ["Lies mit ruhiger Stimme.", "Achte auf Geräusche.", "Suche Wörter mit besonderen Buchstaben."],
    toniTipp: "Lesedetektive finden Hinweise im Text."
  },
  {
    bereich: "Texte verstehen",
    nummer: 1,
    titel: "Toni findet einen Schlüssel",
    level: "schwer",
    text: "Toni spielt im Garten. Unter einem großen Stein entdeckt er einen kleinen Schlüssel. Der Schlüssel ist alt und ein bisschen rostig. Toni ist neugierig. Er ruft Lina. Gemeinsam suchen sie nach einem Schloss. Hinter dem Schuppen finden sie eine kleine Holztür. Der Schlüssel passt. Hinter der Tür liegt ein altes Bilderbuch.",
    aufgaben: ["Lies den Text zweimal.", "Beantworte die Fragen auf Papier.", "Male den Schlüssel oder die Tür."],
    fragen: ["Wo findet Toni den Schlüssel?", "Wen ruft Toni?", "Wo finden die Kinder die Tür?", "Was liegt hinter der Tür?", "Warum ist Toni neugierig?"],
    lesetipps: ["Lies erst den ganzen Text.", "Suche dann die Antwort im Text.", "Lies die passende Stelle noch einmal."],
    toniTipp: "Viele Antworten stehen direkt im Text."
  },
  {
    bereich: "Texte verstehen",
    nummer: 2,
    titel: "Das kleine Kätzchen",
    level: "schwer",
    text: "Auf dem Schulweg hört Toni ein leises Miauen. Neben einer Mauer sitzt ein kleines Kätzchen. Es sieht hungrig aus. Toni bleibt stehen, aber er fasst das Tier nicht an. In der Schule erzählt er seiner Lehrerin davon. Die Lehrerin ruft im Tierheim an. Am Mittag wird das Kätzchen abgeholt. Toni ist froh.",
    aufgaben: ["Lies den Text genau.", "Beantworte die Fragen.", "Schreibe einen passenden Satz ab."],
    fragen: ["Wo hört Toni das Miauen?", "Wie sieht das Kätzchen aus?", "Warum fasst Toni das Tier nicht an?", "Wen informiert Toni?", "Wie fühlt sich Toni am Ende?"],
    lesetipps: ["Achte auf Gefühle.", "Frage dich: Warum macht Toni das?", "Lies den Schluss noch einmal."],
    toniTipp: "Manchmal musst du nachdenken, nicht nur suchen."
  },
  {
    bereich: "Texte verstehen",
    nummer: 3,
    titel: "Ein Tag am Meer",
    level: "schwer",
    text: "Toni fährt mit seiner Familie ans Meer. Der Wind weht stark. Am Strand sammelt Toni Muscheln. Plötzlich rollt eine große Welle bis zu seiner Tasche. Toni erschrickt. Schnell hebt Papa die Tasche hoch. Zum Glück bleibt alles trocken. Danach bauen sie gemeinsam eine Sandburg.",
    aufgaben: ["Beantworte die Fragen auf Papier.", "Male die Sandburg.", "Erzähle die Geschichte einem Partner nach."],
    fragen: ["Wohin fährt Toni?", "Was sammelt Toni?", "Warum erschrickt Toni?", "Wer hilft?", "Was machen alle danach?"],
    lesetipps: ["Achte auf zuerst, plötzlich, danach.", "Lies die spannende Stelle noch einmal.", "Suche das Problem und die Lösung."],
    toniTipp: "Problem und Lösung sind wichtig für das Verstehen."
  },
  {
    bereich: "Texte verstehen",
    nummer: 4,
    titel: "Toni und der Drachenfreund",
    level: "schwer",
    text: "Im Wald findet Toni einen kleinen Drachen. Der Drache sitzt unter einem Baum und schaut traurig. Sein Flügel ist nass. Toni gibt ihm ein Tuch. Der Drache trocknet den Flügel und lächelt. Zum Dank zeigt er Toni eine geheime Lichtung. Dort wachsen blaue Blumen, die im Dunkeln leuchten.",
    aufgaben: ["Lies den Text zweimal.", "Beantworte die Fragen.", "Male die geheime Lichtung."],
    fragen: ["Wo findet Toni den Drachen?", "Warum ist der Drache traurig?", "Wie hilft Toni?", "Was zeigt der Drache Toni?", "Warum ist die Lichtung besonders?"],
    lesetipps: ["Achte darauf, wie sich der Drache fühlt.", "Suche die Hilfe im Text.", "Lies den letzten Satz genau."],
    toniTipp: "Das Besondere steht oft am Ende."
  },
  {
    bereich: "Texte verstehen",
    nummer: 5,
    titel: "Das Gewitter",
    level: "schwer",
    text: "Toni ist mit seiner Klasse auf dem Schulhof. Plötzlich wird der Himmel dunkel. Ein lauter Donner rollt über die Schule. Die Lehrerin ruft alle Kinder zusammen. Schnell gehen sie ins Gebäude. Drinnen zählen sie, ob alle da sind. Toni ist ein bisschen erschrocken, aber auch froh, dass niemand draußen bleiben muss.",
    aufgaben: ["Beantworte die Fragen.", "Unterstreiche im Kopf die wichtigen Stellen.", "Male den Himmel vor dem Gewitter."],
    fragen: ["Wo ist Toni am Anfang?", "Was passiert plötzlich?", "Warum gehen alle ins Gebäude?", "Was machen sie drinnen?", "Wie fühlt sich Toni?"],
    lesetipps: ["Achte auf plötzlich.", "Suche, was die Lehrerin tut.", "Lies den Gefühlssatz noch einmal."],
    toniTipp: "Gefühle helfen dir, die Geschichte zu verstehen."
  },
  {
    bereich: "Texte verstehen",
    nummer: 6,
    titel: "Im Schwimmbad",
    level: "schwer",
    text: "Toni geht mit Oma ins Schwimmbad. Zuerst legt er sein Handtuch auf eine Bank. Dann springt er vorsichtig ins Wasser. Neben ihm übt ein Kind das Tauchen. Toni traut sich erst nicht. Oma winkt ihm zu und lächelt. Da versucht Toni es auch. Nach drei Versuchen taucht er bis zum Boden. Toni ist stolz.",
    aufgaben: ["Lies den Text.", "Beantworte die Fragen.", "Schreibe den Satz ab, der zeigt, dass Toni stolz ist."],
    fragen: ["Mit wem geht Toni ins Schwimmbad?", "Was macht Toni zuerst?", "Warum traut er sich erst nicht?", "Wer macht ihm Mut?", "Was schafft Toni am Ende?"],
    lesetipps: ["Achte auf zuerst, dann, am Ende.", "Suche, wer Toni hilft.", "Lies den letzten Satz genau."],
    toniTipp: "Eine Figur kann sich in einer Geschichte verändern."
  },
  {
    bereich: "Texte verstehen",
    nummer: 7,
    titel: "Der verlorene Ball",
    level: "schwer",
    text: "In der Pause spielt Toni mit Ben Fußball. Ben schießt den Ball zu fest. Der Ball fliegt über den Zaun und landet im Garten des Hausmeisters. Toni will sofort hinterherklettern. Ben hält ihn zurück. Gemeinsam gehen sie zum Hausmeister und fragen freundlich. Der Hausmeister gibt ihnen den Ball zurück.",
    aufgaben: ["Beantworte die Fragen.", "Schreibe auf, was Toni besser nicht machen soll.", "Male den Ball am Zaun."],
    fragen: ["Mit wem spielt Toni Fußball?", "Wohin fliegt der Ball?", "Warum hält Ben Toni zurück?", "Wen fragen die Kinder?", "Warum ist Fragen besser als Klettern?"],
    lesetipps: ["Achte auf das Problem.", "Überlege, welche Lösung sicher ist.", "Lies den letzten Satz noch einmal."],
    toniTipp: "Manche Antworten musst du begründen."
  },
  {
    bereich: "Texte verstehen",
    nummer: 8,
    titel: "Die Überraschungsparty",
    level: "schwer",
    text: "Toni wundert sich. Heute flüstern alle Kinder in der Klasse. Niemand sagt ihm, warum. Nach der Pause soll Toni kurz zur Lehrerin kommen. Als er zurück in die Klasse geht, rufen alle: „Überraschung!“ Auf seinem Platz liegt eine Karte mit vielen Herzen. Toni hat ganz vergessen, dass heute sein Geburtstag ist.",
    aufgaben: ["Lies den Text genau.", "Beantworte die Fragen.", "Male Tonis Platz."],
    fragen: ["Warum wundert sich Toni?", "Was machen die Kinder heimlich?", "Wohin soll Toni nach der Pause?", "Was liegt auf Tonis Platz?", "Warum rufen alle „Überraschung“?"],
    lesetipps: ["Achte auf Hinweise.", "Lies den Anfang nach dem Ende noch einmal.", "Überlege, was die Kinder planen."],
    toniTipp: "Manche Geschichten versteht man am Ende besser."
  },
  {
    bereich: "Texte verstehen",
    nummer: 9,
    titel: "Im Klassenzimmer raschelt es",
    level: "schwer",
    text: "Während der Stillarbeit raschelt es plötzlich in der Leseecke. Alle Kinder schauen auf. Toni legt den Finger an den Mund. Leise geht die Lehrerin zur Bücherkiste. Dort sitzt ein kleiner Igel aus Stoff. Jemand hat ihn zwischen die Bücher gelegt. Die Klasse lacht erleichtert. Danach arbeiten alle weiter.",
    aufgaben: ["Beantworte die Fragen.", "Schreibe auf, warum die Kinder erleichtert sind.", "Male die Leseecke."],
    fragen: ["Wann raschelt es?", "Woher kommt das Geräusch?", "Was findet die Lehrerin?", "Warum lachen die Kinder?", "Warum sollen alle leise sein?"],
    lesetipps: ["Suche den Ort.", "Achte auf die Stimmung.", "Lies den Satz mit erleichtert noch einmal."],
    toniTipp: "Ein Wort kann zeigen, wie sich alle fühlen."
  },
  {
    bereich: "Texte verstehen",
    nummer: 10,
    titel: "Der Schatz im Garten",
    level: "schwer",
    text: "Nach dem Regen glitzert etwas im Garten. Toni läuft hinaus und findet eine kleine Dose im Gras. In der Dose liegen bunte Steine und ein Zettel. Auf dem Zettel steht: „Für den Finder.“ Toni freut sich. Dann sieht er, dass seine kleine Schwester am Fenster lacht. Sie hat den Schatz versteckt.",
    aufgaben: ["Beantworte die Fragen.", "Male die Dose mit dem Schatz.", "Erzähle die Geschichte nach."],
    fragen: ["Wann glitzert etwas im Garten?", "Was findet Toni?", "Was liegt in der Dose?", "Wer hat den Schatz versteckt?", "Warum lacht die Schwester?"],
    lesetipps: ["Lies den Schluss genau.", "Achte darauf, wer etwas getan hat.", "Suche die Antwort im Text."],
    toniTipp: "Das Ende erklärt oft die ganze Geschichte."
  },
  {
    bereich: "Vorlesen",
    nummer: 1,
    titel: "Lies wie ein Roboter",
    level: "mittel",
    text: "",
    aufgaben: ["Lies einen kurzen Abschnitt langsam und deutlich wie ein Roboter."],
    fragen: ["Sprichst du jedes Wort klar?", "Machst du nach jedem Satz eine Pause?", "Kann dein Partner dich verstehen?"],
    lesetipps: ["Lies den Text zuerst leise.", "Lies dann laut.", "Wiederhole schwierige Wörter."],
    toniTipp: "Roboter lesen langsam und genau."
  },
  {
    bereich: "Vorlesen",
    nummer: 2,
    titel: "Lies fröhlich",
    level: "mittel",
    text: "",
    aufgaben: ["Lies eine passende Stelle fröhlich vor."],
    fragen: ["Welche Stelle ist fröhlich?", "Klingt deine Stimme freundlich?", "Wo machst du Pausen?"],
    lesetipps: ["Suche eine schöne Stelle.", "Lächle beim Lesen.", "Lies nicht zu schnell."],
    toniTipp: "Deine Stimme zeigt Gefühle."
  },
  {
    bereich: "Vorlesen",
    nummer: 3,
    titel: "Lies spannend",
    level: "mittel",
    text: "",
    aufgaben: ["Lies eine spannende Stelle besonders spannend vor."],
    fragen: ["Wo wird es spannend?", "Wann wirst du leiser?", "Wann machst du eine Pause?"],
    lesetipps: ["Lies die Stelle zweimal.", "Mache vor wichtigen Wörtern eine Pause.", "Sprich deutlich."],
    toniTipp: "Pausen machen Vorlesen spannend."
  },
  {
    bereich: "Vorlesen",
    nummer: 4,
    titel: "Lies traurig",
    level: "mittel",
    text: "",
    aufgaben: ["Lies eine traurige Stelle mit passender Stimme."],
    fragen: ["Welche Figur ist traurig?", "Warum ist sie traurig?", "Wie klingt deine Stimme?"],
    lesetipps: ["Lies langsam.", "Achte auf Gefühlswörter.", "Lies nicht zu laut."],
    toniTipp: "Stimmen können Gefühle zeigen."
  },
  {
    bereich: "Vorlesen",
    nummer: 5,
    titel: "Lies einem Partner vor",
    level: "mittel",
    text: "",
    aufgaben: ["Lies einem Partner einen Abschnitt vor."],
    fragen: ["Hat dein Partner alles verstanden?", "Wo war es schwierig?", "Kannst du es noch einmal besser lesen?"],
    lesetipps: ["Lies zuerst leise für dich.", "Lies dann laut vor.", "Frage deinen Partner nach einem Tipp."],
    toniTipp: "Gutes Vorlesen darf man üben."
  },
  {
    bereich: "Vorlesen",
    nummer: 6,
    titel: "Lies zweimal",
    level: "mittel",
    text: "",
    aufgaben: ["Lies denselben Abschnitt zweimal."],
    fragen: ["War das zweite Lesen leichter?", "Welche Wörter klappten besser?", "Klingst du flüssiger?"],
    lesetipps: ["Lies beim ersten Mal langsam.", "Lies beim zweiten Mal flüssiger.", "Achte auf Punkte."],
    toniTipp: "Wiederholen macht dich sicherer."
  },
  {
    bereich: "Vorlesen",
    nummer: 7,
    titel: "Punkt-Pause",
    level: "mittel",
    text: "",
    aufgaben: ["Lies einen Abschnitt und mache nach jedem Punkt eine kurze Pause."],
    fragen: ["Hast du jeden Punkt gesehen?", "Hast du Pausen gemacht?", "Klingt dein Lesen ruhiger?"],
    lesetipps: ["Zeige mit dem Finger auf den Punkt.", "Atme kurz ein.", "Lies dann weiter."],
    toniTipp: "Punkte helfen deiner Stimme."
  },
  {
    bereich: "Vorlesen",
    nummer: 8,
    titel: "Schwierige Wörter üben",
    level: "mittel",
    text: "",
    aufgaben: ["Suche drei schwierige Wörter. Lies sie dreimal."],
    fragen: ["Welches Wort ist lang?", "Welches Wort hat viele Silben?", "Kannst du es langsam lesen?"],
    lesetipps: ["Teile lange Wörter in Silben.", "Lies erst langsam.", "Lies dann das ganze Wort."],
    toniTipp: "Silben helfen beim Lesen."
  },
  {
    bereich: "Vorlesen",
    nummer: 9,
    titel: "Vorlesen mit Gefühl",
    level: "mittel",
    text: "",
    aufgaben: ["Suche eine Figur. Lies ihre Sätze mit Gefühl."],
    fragen: ["Wie fühlt sich die Figur?", "Ist sie froh, wütend oder ängstlich?", "Passt deine Stimme?"],
    lesetipps: ["Suche Gefühlswörter.", "Überlege, wie die Figur klingt.", "Lies die Stelle noch einmal."],
    toniTipp: "Gute Vorleser denken an die Figur."
  },
  {
    bereich: "Vorlesen",
    nummer: 10,
    titel: "Lieblingsstelle vorlesen",
    level: "mittel",
    text: "",
    aufgaben: ["Wähle deine Lieblingsstelle und lies sie vor."],
    fragen: ["Warum ist das deine Lieblingsstelle?", "Wem liest du sie vor?", "Was möchtest du besonders schön lesen?"],
    lesetipps: ["Übe die Stelle leise.", "Lies deutlich.", "Mache Pausen."],
    toniTipp: "Eine Lieblingsstelle liest man besonders gern."
  }
];
