const SCHREIBKARTEN = [
  {
    bereich: "Schreibaufgaben",
    nummer: 1,
    titel: "Toni findet etwas",
    auftrag: "Schreibe eine kleine Geschichte in dein Heft.",
    fragen: ["Was findet Toni?", "Wo findet Toni es?", "Was passiert dann?"],
    satzanfaenge: ["Heute ...", "Plötzlich ...", "Dann ..."],
    worthelfer: ["finden", "sehen", "suchen", "freuen"],
    schreibtipps: ["Schreibe mindestens drei Sätze.", "Lies jeden Satz noch einmal.", "Denke an den Punkt am Satzende."],
    toniTipp: "Kontrolliere ein schwieriges Wort im Wörterbuch."
  },
  {
    bereich: "Schreibaufgaben",
    nummer: 2,
    titel: "Mein Lieblingstier",
    auftrag: "Schreibe über dein Lieblingstier.",
    fragen: ["Welches Tier magst du?", "Wie sieht es aus?", "Was kann es gut?"],
    satzanfaenge: ["Mein Lieblingstier ist ...", "Es hat ...", "Es kann ..."],
    worthelfer: ["Tier", "groß", "klein", "schnell", "lieb"],
    schreibtipps: ["Schreibe mindestens drei Sätze.", "Benutze ein Adjektiv.", "Male am Ende dein Tier."],
    toniTipp: "Suche dein Tier im Wörterbuch."
  },
  {
    bereich: "Schreibaufgaben",
    nummer: 3,
    titel: "Ein schöner Tag",
    auftrag: "Schreibe von einem schönen Tag.",
    fragen: ["Was machst du?", "Wer ist dabei?", "Warum ist der Tag schön?"],
    satzanfaenge: ["Heute ist ...", "Ich gehe ...", "Am Ende ..."],
    worthelfer: ["spielen", "lachen", "Freund", "schön", "froh"],
    schreibtipps: ["Schreibe langsam.", "Lass Fingerabstände.", "Lies deinen Text noch einmal."],
    toniTipp: "Denke an Großbuchstaben am Satzanfang."
  },
  {
    bereich: "Schreibaufgaben",
    nummer: 4,
    titel: "Im Schwimmbad",
    auftrag: "Schreibe über einen Besuch im Schwimmbad.",
    fragen: ["Was nimmst du mit?", "Was machst du dort?", "Was macht Spaß?"],
    satzanfaenge: ["Im Schwimmbad ...", "Ich springe ...", "Danach ..."],
    worthelfer: ["Wasser", "schwimmen", "springen", "Handtuch", "Spaß"],
    schreibtipps: ["Schreibe mindestens drei Sätze.", "Setze nach jedem Satz einen Punkt.", "Kontrolliere ein Wort im Wörterbuch."],
    toniTipp: "Sprich schwierige Wörter leise mit."
  },
  {
    bereich: "Schreibaufgaben",
    nummer: 5,
    titel: "Auf dem Spielplatz",
    auftrag: "Schreibe über den Spielplatz.",
    fragen: ["Welche Geräte gibt es?", "Mit wem spielst du?", "Was passiert?"],
    satzanfaenge: ["Auf dem Spielplatz ...", "Zuerst ...", "Dann ..."],
    worthelfer: ["Schaukel", "Rutsche", "Ball", "spielen", "lachen"],
    schreibtipps: ["Schreibe ordentlich.", "Nutze mindestens ein Verb.", "Lies deinen Text einem Partner vor."],
    toniTipp: "Prüfe, ob man deine Wörter gut lesen kann."
  },
  {
    bereich: "Schreibaufgaben",
    nummer: 6,
    titel: "Mein Lieblingsessen",
    auftrag: "Schreibe über dein Lieblingsessen.",
    fragen: ["Was isst du gern?", "Wie schmeckt es?", "Wann isst du es?"],
    satzanfaenge: ["Mein Lieblingsessen ist ...", "Es schmeckt ...", "Ich esse es ..."],
    worthelfer: ["essen", "lecker", "süß", "Brot", "Apfel"],
    schreibtipps: ["Schreibe mindestens drei Sätze.", "Benutze ein Adjektiv.", "Suche ein Essenswort im Wörterbuch."],
    toniTipp: "Denke an den Punkt am Satzende."
  },
  {
    bereich: "Schreibaufgaben",
    nummer: 7,
    titel: "Der geheime Brief",
    auftrag: "Schreibe eine Geschichte über einen geheimen Brief.",
    fragen: ["Wer findet den Brief?", "Was steht darin?", "Was passiert danach?"],
    satzanfaenge: ["Plötzlich ...", "In dem Brief steht ...", "Danach ..."],
    worthelfer: ["Brief", "lesen", "finden", "geheim", "schreiben"],
    schreibtipps: ["Schreibe einen spannenden Anfang.", "Schreibe mindestens vier Sätze.", "Lies deinen Text noch einmal."],
    toniTipp: "Beginne jeden Satz groß."
  },
  {
    bereich: "Schreibaufgaben",
    nummer: 8,
    titel: "Ein Tier braucht Hilfe",
    auftrag: "Schreibe eine Geschichte.",
    fragen: ["Welches Tier ist es?", "Was ist passiert?", "Wie hilfst du?"],
    satzanfaenge: ["Ein kleines Tier ...", "Es braucht Hilfe, weil ...", "Zum Glück ..."],
    worthelfer: ["helfen", "Tier", "retten", "traurig", "froh"],
    schreibtipps: ["Schreibe mindestens vier Sätze.", "Erzähle genau, wie geholfen wird.", "Kontrolliere ein Tierwort."],
    toniTipp: "Suche passende Wörter im Wörterbuch."
  },
  {
    bereich: "Schreibaufgaben",
    nummer: 9,
    titel: "Im Garten",
    auftrag: "Schreibe über einen Garten.",
    fragen: ["Was wächst dort?", "Welche Tiere siehst du?", "Was machst du?"],
    satzanfaenge: ["Im Garten ...", "Ich sehe ...", "Unter dem Baum ..."],
    worthelfer: ["Garten", "Blume", "Baum", "Wiese", "Biene"],
    schreibtipps: ["Schreibe mindestens drei Sätze.", "Benutze ein Adjektiv.", "Male am Ende ein Bild."],
    toniTipp: "Lies deinen Satz nach dem Schreiben sofort noch einmal."
  },
  {
    bereich: "Schreibaufgaben",
    nummer: 10,
    titel: "Ein Ausflug",
    auftrag: "Schreibe über einen Ausflug.",
    fragen: ["Wohin gehst du?", "Wer kommt mit?", "Was erlebst du?"],
    satzanfaenge: ["Heute machen wir ...", "Wir fahren ...", "Dort sehen wir ..."],
    worthelfer: ["Ausflug", "fahren", "sehen", "Reise", "freuen"],
    schreibtipps: ["Schreibe in der richtigen Reihenfolge.", "Nutze zuerst, dann, am Ende.", "Setze Punkte."],
    toniTipp: "Ordne deine Geschichte: Anfang, Mitte, Ende."
  },
  {
    bereich: "Schreibaufgaben",
    nummer: 11,
    titel: "Der verlorene Ball",
    auftrag: "Schreibe eine Geschichte über einen Ball.",
    fragen: ["Wer verliert den Ball?", "Wo liegt er?", "Wer findet ihn?"],
    satzanfaenge: ["Toni spielt ...", "Plötzlich rollt ...", "Zum Glück ..."],
    worthelfer: ["Ball", "rollen", "suchen", "finden", "spielen"],
    schreibtipps: ["Schreibe mindestens vier Sätze.", "Benutze ein Verb.", "Kontrolliere Ball oder spielen."],
    toniTipp: "Schreibe langsam und deutlich."
  },
  {
    bereich: "Schreibaufgaben",
    nummer: 12,
    titel: "Ein Regentag",
    auftrag: "Schreibe über einen Regentag.",
    fragen: ["Was machst du drinnen?", "Was hörst du draußen?", "Wie endet der Tag?"],
    satzanfaenge: ["Heute regnet es.", "Ich höre ...", "Am Ende ..."],
    worthelfer: ["Regen", "Wolke", "hören", "spielen", "lesen"],
    schreibtipps: ["Schreibe mindestens drei Sätze.", "Benutze ein Geräuschwort.", "Lies deinen Text noch einmal."],
    toniTipp: "Denke an Fingerabstände."
  },
  {
    bereich: "Schreibaufgaben",
    nummer: 13,
    titel: "Mein bester Freund",
    auftrag: "Schreibe über einen Freund oder eine Freundin.",
    fragen: ["Wie heißt dein Freund?", "Was macht ihr zusammen?", "Warum magst du ihn oder sie?"],
    satzanfaenge: ["Mein Freund heißt ...", "Wir spielen ...", "Ich mag ..."],
    worthelfer: ["Freund", "Freundin", "spielen", "nett", "helfen"],
    schreibtipps: ["Schreibe freundlich.", "Benutze ein Adjektiv.", "Kontrolliere Freund oder Freundin."],
    toniTipp: "Schreibe Namen groß."
  },
  {
    bereich: "Schreibaufgaben",
    nummer: 14,
    titel: "Das besondere Geschenk",
    auftrag: "Schreibe über ein besonderes Geschenk.",
    fragen: ["Wer bekommt es?", "Was ist darin?", "Warum ist es besonders?"],
    satzanfaenge: ["Ich bekomme ...", "In dem Paket ist ...", "Ich freue mich, weil ..."],
    worthelfer: ["Geschenk", "Paket", "freuen", "schön", "öffnen"],
    schreibtipps: ["Schreibe mindestens vier Sätze.", "Beschreibe das Geschenk genau.", "Setze Punkte."],
    toniTipp: "Lies deinen Text wie ein Detektiv."
  },
  {
    bereich: "Schreibaufgaben",
    nummer: 15,
    titel: "In der Schule",
    auftrag: "Schreibe über die Schule.",
    fragen: ["Was machst du gern?", "Wo sitzt du?", "Wer hilft dir?"],
    satzanfaenge: ["In der Schule ...", "Ich lerne ...", "Mir hilft ..."],
    worthelfer: ["Schule", "Klasse", "Heft", "lesen", "schreiben"],
    schreibtipps: ["Schreibe mindestens drei Sätze.", "Suche ein Schulwort im Wörterbuch.", "Beginne jeden Satz groß."],
    toniTipp: "Kontrolliere ein Wort mit sch."
  },
  {
    bereich: "Schreibaufgaben",
    nummer: 16,
    titel: "Ein lustiger Traum",
    auftrag: "Schreibe über einen verrückten Traum.",
    fragen: ["Was träumst du?", "Wer kommt vor?", "Was ist verrückt?"],
    satzanfaenge: ["Ich träume ...", "Plötzlich ...", "Alle lachen, weil ..."],
    worthelfer: ["Traum", "lustig", "plötzlich", "lachen", "verrückt"],
    schreibtipps: ["Schreibe spannend oder lustig.", "Schreibe mindestens vier Sätze.", "Lies deinen Text vor."],
    toniTipp: "In Träumen darf alles passieren."
  },
  {
    bereich: "Schreibaufgaben",
    nummer: 17,
    titel: "Toni ist mutig",
    auftrag: "Schreibe eine Mut-Geschichte.",
    fragen: ["Wovor hat Toni Angst?", "Was macht er trotzdem?", "Wer hilft ihm?"],
    satzanfaenge: ["Toni hat Angst vor ...", "Trotzdem ...", "Am Ende ..."],
    worthelfer: ["mutig", "Angst", "helfen", "stark", "schaffen"],
    schreibtipps: ["Schreibe mit Gefühl.", "Benutze ein Gefühlswort.", "Kontrolliere mutig oder Angst."],
    toniTipp: "Erzähle, wie Toni sich fühlt."
  },
  {
    bereich: "Schreibaufgaben",
    nummer: 18,
    titel: "Im Wald",
    auftrag: "Schreibe über den Wald.",
    fragen: ["Was sieht Toni?", "Welche Geräusche hört er?", "Was entdeckt er?"],
    satzanfaenge: ["Im Wald ...", "Toni hört ...", "Hinter einem Baum ..."],
    worthelfer: ["Wald", "Baum", "Tier", "hören", "entdecken"],
    schreibtipps: ["Schreibe mindestens vier Sätze.", "Benutze sehen oder hören.", "Male ein Waldbild."],
    toniTipp: "Mache deine Geschichte spannend."
  },
  {
    bereich: "Schreibaufgaben",
    nummer: 19,
    titel: "Mein Wunsch",
    auftrag: "Schreibe über einen Wunsch.",
    fragen: ["Was wünschst du dir?", "Warum?", "Was würdest du damit machen?"],
    satzanfaenge: ["Ich wünsche mir ...", "Das wäre schön, weil ...", "Dann könnte ich ..."],
    worthelfer: ["Wunsch", "wünschen", "freuen", "schön", "bekommen"],
    schreibtipps: ["Schreibe mindestens drei Sätze.", "Begründe deinen Wunsch mit weil.", "Lies den Text noch einmal."],
    toniTipp: "Das Wort weil hilft dir beim Begründen."
  },
  {
    bereich: "Schreibaufgaben",
    nummer: 20,
    titel: "Heute bin ich stolz",
    auftrag: "Schreibe über etwas, das du geschafft hast.",
    fragen: ["Was hast du geschafft?", "Warum war es schwer?", "Wer freut sich mit dir?"],
    satzanfaenge: ["Heute bin ich stolz, weil ...", "Zuerst war es schwer.", "Dann ..."],
    worthelfer: ["stolz", "schaffen", "schwer", "freuen", "üben"],
    schreibtipps: ["Schreibe ehrlich.", "Benutze weil.", "Lies deinen Text noch einmal."],
    toniTipp: "Ein Text darf von dir erzählen."
  },
  {
    bereich: "Mini-Bücher",
    nummer: 1,
    titel: "Toni macht Ferien",
    auftrag: "Gestalte ein Mini-Buch.",
    fragen: ["Wohin fährt Toni?", "Was packt er ein?", "Was erlebt er?"],
    satzanfaenge: ["Toni fährt ...", "In seinem Koffer ...", "Am Ferienort ..."],
    worthelfer: ["Ferien", "Urlaub", "Koffer", "Reise", "Sonne"],
    schreibtipps: ["Schreibe auf jede Seite einen Satz.", "Male zu jeder Seite ein Bild.", "Erzähle der Reihe nach."],
    toniTipp: "Ein Mini-Buch braucht Anfang, Mitte und Ende."
  },
  {
    bereich: "Mini-Bücher",
    nummer: 2,
    titel: "Toni hat Geburtstag",
    auftrag: "Gestalte ein Geburtstags-Mini-Buch.",
    fragen: ["Wer kommt?", "Was gibt es zu essen?", "Welches Geschenk bekommt Toni?"],
    satzanfaenge: ["Heute hat Toni Geburtstag.", "Die Gäste ...", "Zum Schluss ..."],
    worthelfer: ["Geburtstag", "Geschenk", "Kuchen", "feiern", "freuen"],
    schreibtipps: ["Schreibe mindestens sechs Seiten.", "Nutze viele Namenwörter.", "Male eine Geburtstagsseite."],
    toniTipp: "Denke an einen schönen Schluss."
  },
  {
    bereich: "Mini-Bücher",
    nummer: 3,
    titel: "Toni rettet ein Tier",
    auftrag: "Gestalte ein Mini-Buch über eine Rettung.",
    fragen: ["Welches Tier braucht Hilfe?", "Was ist passiert?", "Wie rettet Toni es?"],
    satzanfaenge: ["Toni sieht ...", "Das Tier braucht Hilfe.", "Schnell ..."],
    worthelfer: ["Tier", "retten", "helfen", "Angst", "froh"],
    schreibtipps: ["Schreibe genau, was passiert.", "Benutze zuerst, dann, am Ende.", "Kontrolliere das Tierwort."],
    toniTipp: "Eine Rettungsgeschichte ist besonders spannend."
  },
  {
    bereich: "Mini-Bücher",
    nummer: 4,
    titel: "Toni trifft einen Drachen",
    auftrag: "Gestalte ein Drachen-Mini-Buch.",
    fragen: ["Wo trifft Toni den Drachen?", "Ist der Drache nett?", "Was erleben sie?"],
    satzanfaenge: ["Plötzlich sieht Toni ...", "Der Drache sagt ...", "Gemeinsam ..."],
    worthelfer: ["Drache", "Feuer", "mutig", "Freund", "fliegen"],
    schreibtipps: ["Schreibe fantasievoll.", "Erfinde ein Problem.", "Schreibe eine Lösung."],
    toniTipp: "Auch ein Drache kann freundlich sein."
  },
  {
    bereich: "Mini-Bücher",
    nummer: 5,
    titel: "Toni besucht die WM",
    auftrag: "Gestalte ein Fußball-Mini-Buch.",
    fragen: ["Welche Mannschaft sieht Toni?", "Was passiert im Stadion?", "Wer gewinnt?"],
    satzanfaenge: ["Toni geht ins Stadion.", "Die Fans rufen ...", "Am Ende ..."],
    worthelfer: ["Ball", "Tor", "spielen", "gewinnen", "freuen"],
    schreibtipps: ["Schreibe spannend wie ein Reporter.", "Nutze Fußballwörter.", "Male ein Stadion."],
    toniTipp: "Du kannst die Wörter im Wörterbuch suchen."
  },
  {
    bereich: "Mini-Bücher",
    nummer: 6,
    titel: "Toni findet einen Schatz",
    auftrag: "Gestalte ein Schatz-Mini-Buch.",
    fragen: ["Wo liegt der Schatz?", "Was ist darin?", "Wem gehört er?"],
    satzanfaenge: ["Im Sand findet Toni ...", "In der Kiste ...", "Plötzlich ..."],
    worthelfer: ["Schatz", "Kiste", "finden", "glänzen", "suchen"],
    schreibtipps: ["Schreibe einen spannenden Fund.", "Beschreibe den Schatz.", "Denke an Punkte."],
    toniTipp: "Ein Schatz muss nicht aus Gold sein."
  },
  {
    bereich: "Mini-Bücher",
    nummer: 7,
    titel: "Toni im Regen",
    auftrag: "Gestalte ein Mini-Buch über Regen.",
    fragen: ["Wo ist Toni?", "Wie schützt er sich?", "Was passiert am Ende?"],
    satzanfaenge: ["Es regnet stark.", "Toni sucht ...", "Zum Glück ..."],
    worthelfer: ["Regen", "nass", "Schirm", "Wolke", "laufen"],
    schreibtipps: ["Schreibe mindestens fünf Seiten.", "Benutze Wetterwörter.", "Male Regen dazu."],
    toniTipp: "Schreibe, wie sich Toni fühlt."
  },
  {
    bereich: "Mini-Bücher",
    nummer: 8,
    titel: "Toni baut eine Höhle",
    auftrag: "Gestalte ein Höhlen-Mini-Buch.",
    fragen: ["Woraus baut Toni sie?", "Wer darf hinein?", "Was passiert dort?"],
    satzanfaenge: ["Toni baut ...", "In der Höhle ...", "Dann kommt ..."],
    worthelfer: ["Höhle", "Decke", "Kissen", "bauen", "gemütlich"],
    schreibtipps: ["Schreibe auf jede Seite einen Satz.", "Nutze Wörter aus „Zum Kuscheln“.", "Male deine Höhle."],
    toniTipp: "Beschreibe, wie die Höhle aussieht."
  },
  {
    bereich: "Mini-Bücher",
    nummer: 9,
    titel: "Toni am Meer",
    auftrag: "Gestalte ein Meer-Mini-Buch.",
    fragen: ["Was sieht Toni?", "Was sammelt er?", "Wen trifft er?"],
    satzanfaenge: ["Am Meer ...", "Toni sammelt ...", "Im Wasser ..."],
    worthelfer: ["Meer", "Strand", "Muschel", "Seestern", "Sand"],
    schreibtipps: ["Schreibe mindestens fünf Seiten.", "Benutze Sommerwörter.", "Kontrolliere ein schwieriges Wort."],
    toniTipp: "Das Wörterbuch hilft dir bei Meerwörtern."
  },
  {
    bereich: "Mini-Bücher",
    nummer: 10,
    titel: "Toni im Zoo",
    auftrag: "Gestalte ein Zoo-Mini-Buch.",
    fragen: ["Welche Tiere sieht Toni?", "Welches Tier mag er?", "Was passiert?"],
    satzanfaenge: ["Im Zoo sieht Toni ...", "Besonders mag er ...", "Dann ..."],
    worthelfer: ["Zoo", "Tier", "Elefant", "Affe", "Löwe"],
    schreibtipps: ["Schreibe über mehrere Tiere.", "Nutze Tierwörter.", "Male dein Lieblingstier."],
    toniTipp: "Suche die Tiere im Wörterbuch."
  },
  {
    bereich: "Mini-Bücher",
    nummer: 11,
    titel: "Toni fährt Zug",
    auftrag: "Gestalte ein Reise-Mini-Buch.",
    fragen: ["Wohin fährt Toni?", "Wer sitzt neben ihm?", "Was sieht er aus dem Fenster?"],
    satzanfaenge: ["Toni steigt in den Zug.", "Neben ihm sitzt ...", "Aus dem Fenster sieht er ..."],
    worthelfer: ["Zug", "Reise", "fahren", "Fenster", "sehen"],
    schreibtipps: ["Schreibe die Reise der Reihe nach.", "Nutze zuerst, dann, danach.", "Kontrolliere Zug oder Reise."],
    toniTipp: "Eine Reisegeschichte hat viele Stationen."
  },
  {
    bereich: "Mini-Bücher",
    nummer: 12,
    titel: "Toni und der Zauberstab",
    auftrag: "Gestalte ein Zauber-Mini-Buch.",
    fragen: ["Wo findet Toni ihn?", "Was zaubert er?", "Geht etwas schief?"],
    satzanfaenge: ["Toni findet ...", "Er zaubert ...", "Auf einmal ..."],
    worthelfer: ["Zauberstab", "zaubern", "plötzlich", "Idee", "lachen"],
    schreibtipps: ["Schreibe fantasievoll.", "Erfinde eine Überraschung.", "Schreibe eine Lösung."],
    toniTipp: "Zaubergeschichten dürfen verrückt sein."
  },
  {
    bereich: "Mini-Bücher",
    nummer: 13,
    titel: "Toni verliert seinen Ranzen",
    auftrag: "Gestalte ein Mini-Buch über eine Suche.",
    fragen: ["Wo sucht Toni?", "Wer hilft ihm?", "Wo findet er ihn?"],
    satzanfaenge: ["Toni sucht seinen Ranzen.", "Zuerst schaut er ...", "Endlich ..."],
    worthelfer: ["Ranzen", "suchen", "finden", "helfen", "Schule"],
    schreibtipps: ["Schreibe eine Suchgeschichte.", "Nutze zuerst, dann, endlich.", "Kontrolliere ein Schulwort."],
    toniTipp: "Schreibe, was Toni denkt."
  },
  {
    bereich: "Mini-Bücher",
    nummer: 14,
    titel: "Toni auf dem Bauernhof",
    auftrag: "Gestalte ein Bauernhof-Mini-Buch.",
    fragen: ["Welche Tiere sieht Toni?", "Was darf er füttern?", "Was lernt er?"],
    satzanfaenge: ["Auf dem Bauernhof ...", "Toni füttert ...", "Am Ende weiß er ..."],
    worthelfer: ["Bauernhof", "Kuh", "Schwein", "Pferd", "füttern"],
    schreibtipps: ["Nutze Tierwörter.", "Schreibe mindestens fünf Seiten.", "Male einen Bauernhof."],
    toniTipp: "Kontrolliere die Tiernamen im Wörterbuch."
  },
  {
    bereich: "Mini-Bücher",
    nummer: 15,
    titel: "Toni im Zirkus",
    auftrag: "Gestalte ein Zirkus-Mini-Buch.",
    fragen: ["Welche Kunststücke sieht er?", "Darf er mitmachen?", "Was klappt?"],
    satzanfaenge: ["Im Zirkus ...", "Toni staunt ...", "Dann darf er ..."],
    worthelfer: ["Zirkus", "staunen", "lachen", "mutig", "springen"],
    schreibtipps: ["Schreibe spannend und lustig.", "Benutze ein Gefühlswort.", "Schreibe einen Schluss."],
    toniTipp: "Ein Zirkus ist voller Überraschungen."
  },
  {
    bereich: "Mini-Bücher",
    nummer: 16,
    titel: "Toni und das Monster",
    auftrag: "Gestalte ein Monster-Mini-Buch.",
    fragen: ["Wo wohnt das Monster?", "Ist es gefährlich?", "Wie endet die Geschichte?"],
    satzanfaenge: ["In der Nacht ...", "Das Monster ...", "Zum Glück ..."],
    worthelfer: ["Monster", "Angst", "mutig", "Freund", "lachen"],
    schreibtipps: ["Mache es spannend.", "Schreibe, ob das Monster nett ist.", "Kontrolliere ein Gefühlswort."],
    toniTipp: "Ein Monster kann auch lieb sein."
  },
  {
    bereich: "Mini-Bücher",
    nummer: 17,
    titel: "Toni entdeckt eine Tür",
    auftrag: "Gestalte ein geheimnisvolles Mini-Buch.",
    fragen: ["Wo ist die Tür?", "Was ist dahinter?", "Geht Toni hinein?"],
    satzanfaenge: ["Hinter dem Schrank ...", "Toni öffnet die Tür.", "Dahinter ..."],
    worthelfer: ["Tür", "öffnen", "geheim", "dahinter", "entdecken"],
    schreibtipps: ["Schreibe spannend.", "Benutze Plötzlich.", "Schreibe ein überraschendes Ende."],
    toniTipp: "Lass die Leser neugierig werden."
  },
  {
    bereich: "Mini-Bücher",
    nummer: 18,
    titel: "Toni im Weltraum",
    auftrag: "Gestalte ein Weltraum-Mini-Buch.",
    fragen: ["Wie kommt Toni dorthin?", "Was sieht er?", "Wie kommt er zurück?"],
    satzanfaenge: ["Toni fliegt ...", "Im Weltraum sieht er ...", "Zurück kommt er ..."],
    worthelfer: ["Mond", "Stern", "fliegen", "Erde", "Rakete"],
    schreibtipps: ["Schreibe fantasievoll.", "Nutze Ortswörter.", "Male den Weltraum."],
    toniTipp: "Du darfst dir alles ausdenken."
  },
  {
    bereich: "Mini-Bücher",
    nummer: 19,
    titel: "Toni und der Schneemann",
    auftrag: "Gestalte ein Winter-Mini-Buch.",
    fragen: ["Wer baut ihn?", "Was fehlt ihm?", "Was passiert in der Sonne?"],
    satzanfaenge: ["Im Schnee ...", "Der Schneemann hat ...", "Als die Sonne scheint ..."],
    worthelfer: ["Schnee", "Sonne", "bauen", "kalt", "schmelzen"],
    schreibtipps: ["Schreibe mindestens fünf Seiten.", "Erzähle der Reihe nach.", "Denke an Punkte."],
    toniTipp: "Schreibe auch, wie Toni sich fühlt."
  },
  {
    bereich: "Mini-Bücher",
    nummer: 20,
    titel: "Toni schreibt ein Buch",
    auftrag: "Gestalte ein Mini-Buch über ein Buch.",
    fragen: ["Worüber schreibt Toni?", "Wer liest es?", "Warum ist Toni stolz?"],
    satzanfaenge: ["Toni schreibt ...", "In seinem Buch ...", "Am Ende ..."],
    worthelfer: ["Buch", "schreiben", "lesen", "stolz", "Geschichte"],
    schreibtipps: ["Schreibe über das Schreiben.", "Nutze Anfang, Mitte, Ende.", "Lies dein Mini-Buch vor."],
    toniTipp: "Du bist auch ein Autor oder eine Autorin."
  },
  {
    bereich: "Geschichtenideen",
    nummer: 1,
    titel: "Ein Schlüssel liegt im Gras",
    auftrag: "Schreibe eine Geschichte zu dieser Idee.",
    fragen: ["Wem gehört der Schlüssel?", "Welche Tür öffnet er?", "Was findet Toni?"],
    satzanfaenge: ["Im Gras liegt ...", "Toni hebt ihn auf.", "Der Schlüssel passt ..."],
    worthelfer: ["Schlüssel", "Gras", "Tür", "finden", "öffnen"],
    schreibtipps: ["Schreibe spannend.", "Erfinde eine Überraschung.", "Lies deinen Text noch einmal."],
    toniTipp: "Eine gute Geschichte hat ein Geheimnis."
  },
  {
    bereich: "Geschichtenideen",
    nummer: 2,
    titel: "Im Klassenzimmer raschelt es",
    auftrag: "Schreibe eine Schulgeschichte.",
    fragen: ["Woher kommt das Geräusch?", "Wer versteckt sich?", "Was macht die Klasse?"],
    satzanfaenge: ["Im Klassenzimmer ...", "Plötzlich raschelt es.", "Alle schauen ..."],
    worthelfer: ["Klasse", "hören", "Geräusch", "verstecken", "finden"],
    schreibtipps: ["Beginne spannend.", "Schreibe mindestens vier Sätze.", "Nutze ein Geräuschwort."],
    toniTipp: "Lies deinen Anfang besonders genau."
  },
  {
    bereich: "Geschichtenideen",
    nummer: 3,
    titel: "Ein Ball rollt weg",
    auftrag: "Schreibe eine Geschichte über einen Ball.",
    fragen: ["Wohin rollt er?", "Wer läuft hinterher?", "Was passiert?"],
    satzanfaenge: ["Der Ball rollt ...", "Toni rennt ...", "Dann ..."],
    worthelfer: ["Ball", "rollen", "rennen", "suchen", "finden"],
    schreibtipps: ["Schreibe in der richtigen Reihenfolge.", "Setze Punkte.", "Nutze ein Verb."],
    toniTipp: "Verben machen deine Geschichte lebendig."
  },
  {
    bereich: "Geschichtenideen",
    nummer: 4,
    titel: "Ein Vogel kann sprechen",
    auftrag: "Schreibe eine Fantasiegeschichte.",
    fragen: ["Was sagt der Vogel?", "Wer hört ihn?", "Was soll Toni tun?"],
    satzanfaenge: ["Auf dem Baum sitzt ...", "Der Vogel sagt ...", "Toni staunt ..."],
    worthelfer: ["Vogel", "sprechen", "hören", "staunen", "helfen"],
    schreibtipps: ["Schreibe, was der Vogel sagt.", "Benutze Anführungszeichen nur, wenn du sie kennst.", "Schreibe einen Schluss."],
    toniTipp: "Du darfst dir eine verrückte Botschaft ausdenken."
  },
  {
    bereich: "Geschichtenideen",
    nummer: 5,
    titel: "Eine Schatzkarte taucht auf",
    auftrag: "Schreibe eine Schatzgeschichte.",
    fragen: ["Wo findet Toni die Karte?", "Was zeigt die Karte?", "Wer kommt mit?"],
    satzanfaenge: ["Toni findet eine Karte.", "Darauf sieht er ...", "Gemeinsam ..."],
    worthelfer: ["Schatz", "Karte", "suchen", "Weg", "finden"],
    schreibtipps: ["Beschreibe den Weg.", "Schreibe mindestens fünf Sätze.", "Kontrolliere Schatz oder Karte."],
    toniTipp: "Eine Karte führt zu einem Ziel."
  },
  {
    bereich: "Geschichtenideen",
    nummer: 6,
    titel: "Der Ranzen ist plötzlich leer",
    auftrag: "Schreibe eine kleine Detektivgeschichte.",
    fragen: ["Was fehlt?", "Wer hat es genommen?", "Wie löst sich das Rätsel?"],
    satzanfaenge: ["Toni öffnet den Ranzen.", "Oh nein, ...", "Am Ende ..."],
    worthelfer: ["Ranzen", "leer", "suchen", "finden", "Detektiv"],
    schreibtipps: ["Schreibe ein Rätsel.", "Gib Hinweise.", "Löse das Rätsel am Ende."],
    toniTipp: "Detektive schauen genau hin."
  },
  {
    bereich: "Geschichtenideen",
    nummer: 7,
    titel: "Eine Wolke sieht aus wie ein Tier",
    auftrag: "Schreibe eine Wolkengeschichte.",
    fragen: ["Welches Tier ist es?", "Bewegt es sich?", "Was passiert dann?"],
    satzanfaenge: ["Am Himmel ...", "Die Wolke sieht aus wie ...", "Plötzlich ..."],
    worthelfer: ["Wolke", "Himmel", "Tier", "sehen", "fliegen"],
    schreibtipps: ["Schreibe fantasievoll.", "Benutze ein Tierwort.", "Male die Wolke dazu."],
    toniTipp: "Fantasie macht Texte besonders."
  },
  {
    bereich: "Geschichtenideen",
    nummer: 8,
    titel: "Toni hört Musik",
    auftrag: "Schreibe eine Geschichte über Musik.",
    fragen: ["Woher kommt die Musik?", "Wer spielt?", "Darf Toni mitmachen?"],
    satzanfaenge: ["Toni hört Musik.", "Sie kommt aus ...", "Dann ..."],
    worthelfer: ["Musik", "hören", "singen", "spielen", "Freude"],
    schreibtipps: ["Schreibe, was Toni hört.", "Nutze ein Gefühlswort.", "Lies deinen Text laut vor."],
    toniTipp: "Musik kann fröhlich oder leise sein."
  },
  {
    bereich: "Geschichtenideen",
    nummer: 9,
    titel: "Ein Paket steht vor der Tür",
    auftrag: "Schreibe eine Paketgeschichte.",
    fragen: ["Für wen ist es?", "Was ist darin?", "Wer hat es geschickt?"],
    satzanfaenge: ["Vor der Tür steht ...", "Toni öffnet ...", "Darin liegt ..."],
    worthelfer: ["Paket", "Tür", "öffnen", "Geschenk", "staunen"],
    schreibtipps: ["Mache die Leser neugierig.", "Beschreibe den Inhalt.", "Schreibe einen Schluss."],
    toniTipp: "Verrate nicht sofort alles."
  },
  {
    bereich: "Geschichtenideen",
    nummer: 10,
    titel: "Der Garten leuchtet",
    auftrag: "Schreibe eine geheimnisvolle Geschichte.",
    fragen: ["Warum leuchtet der Garten?", "Wer ist dort?", "Was entdeckt Toni?"],
    satzanfaenge: ["In der Nacht ...", "Der Garten leuchtet.", "Unter der Blume ..."],
    worthelfer: ["Garten", "leuchten", "Nacht", "entdecken", "Licht"],
    schreibtipps: ["Schreibe spannend.", "Nutze Nachtwörter.", "Kontrolliere Garten im Wörterbuch."],
    toniTipp: "Geheimnisse machen Geschichten spannend."
  },
  {
    bereich: "Geschichtenideen",
    nummer: 11,
    titel: "Ein kleiner Drache friert",
    auftrag: "Schreibe eine Drachen-Geschichte.",
    fragen: ["Wo findet Toni ihn?", "Wie hilft er?", "Was schenkt der Drache?"],
    satzanfaenge: ["Toni findet einen Drachen.", "Der Drache friert.", "Toni hilft ..."],
    worthelfer: ["Drache", "frieren", "helfen", "Decke", "schenken"],
    schreibtipps: ["Schreibe mit Gefühl.", "Beschreibe den Drachen.", "Schreibe ein freundliches Ende."],
    toniTipp: "Nicht jeder Drache ist gefährlich."
  },
  {
    bereich: "Geschichtenideen",
    nummer: 12,
    titel: "Die Uhr bleibt stehen",
    auftrag: "Schreibe eine Zeitgeschichte.",
    fragen: ["Wann passiert es?", "Was ist anders?", "Wie geht die Zeit weiter?"],
    satzanfaenge: ["Plötzlich bleibt die Uhr stehen.", "Alles ist still.", "Dann ..."],
    worthelfer: ["Uhr", "Zeit", "stehen", "warten", "weiter"],
    schreibtipps: ["Schreibe geheimnisvoll.", "Nutze Plötzlich.", "Lies deinen Text noch einmal."],
    toniTipp: "Ein seltsamer Anfang macht neugierig."
  },
  {
    bereich: "Geschichtenideen",
    nummer: 13,
    titel: "Ein Schuh ist verschwunden",
    auftrag: "Schreibe eine Suchgeschichte.",
    fragen: ["Wem gehört der Schuh?", "Wo liegt er?", "Wer hat ihn versteckt?"],
    satzanfaenge: ["Ein Schuh fehlt.", "Toni sucht ...", "Unter dem ..."],
    worthelfer: ["Schuh", "suchen", "finden", "verstecken", "lachen"],
    schreibtipps: ["Schreibe die Suche der Reihe nach.", "Nutze Ortswörter.", "Setze Punkte."],
    toniTipp: "Ortswörter helfen beim Erzählen."
  },
  {
    bereich: "Geschichtenideen",
    nummer: 14,
    titel: "Ein Stern fällt vom Himmel",
    auftrag: "Schreibe eine Sternengeschichte.",
    fragen: ["Wo landet der Stern?", "Kann Toni ihn anfassen?", "Was wünscht er sich?"],
    satzanfaenge: ["Ein Stern fällt ...", "Er landet ...", "Toni wünscht sich ..."],
    worthelfer: ["Stern", "Himmel", "fallen", "Wunsch", "leuchten"],
    schreibtipps: ["Schreibe fantasievoll.", "Benutze ein Wunsch-Wort.", "Male den Stern."],
    toniTipp: "Ein Wunsch macht deine Geschichte schön."
  },
  {
    bereich: "Geschichtenideen",
    nummer: 15,
    titel: "Im Buch ist eine Tür",
    auftrag: "Schreibe eine magische Geschichte.",
    fragen: ["Welches Buch ist es?", "Wohin führt die Tür?", "Geht Toni hinein?"],
    satzanfaenge: ["Toni liest ein Buch.", "Auf der Seite ist eine Tür.", "Dahinter ..."],
    worthelfer: ["Buch", "Tür", "lesen", "öffnen", "geheim"],
    schreibtipps: ["Schreibe spannend.", "Erfinde eine neue Welt.", "Schreibe ein Ende."],
    toniTipp: "Bücher können in Geschichten alles."
  },
  {
    bereich: "Geschichtenideen",
    nummer: 16,
    titel: "Eine Flaschenpost kommt an",
    auftrag: "Schreibe eine Meer-Geschichte.",
    fragen: ["Was steht darin?", "Wer braucht Hilfe?", "Wohin geht Toni?"],
    satzanfaenge: ["Am Strand findet Toni ...", "In der Flasche steht ...", "Schnell ..."],
    worthelfer: ["Flasche", "Meer", "Hilfe", "Strand", "Reise"],
    schreibtipps: ["Schreibe eine Hilfegeschichte.", "Nutze Meerwörter.", "Kontrolliere Flasche im Wörterbuch."],
    toniTipp: "Eine Flaschenpost braucht eine Botschaft."
  },
  {
    bereich: "Geschichtenideen",
    nummer: 17,
    titel: "Der Pausenhof ist leer",
    auftrag: "Schreibe eine Schulhofgeschichte.",
    fragen: ["Wo sind alle Kinder?", "Was hört Toni?", "Wen findet er?"],
    satzanfaenge: ["Der Pausenhof ist leer.", "Toni hört ...", "Hinter der Schaukel ..."],
    worthelfer: ["Pausenhof", "leer", "hören", "finden", "Schaukel"],
    schreibtipps: ["Schreibe spannend.", "Benutze hören und sehen.", "Lies deinen Text noch einmal."],
    toniTipp: "Schreibe, was Toni zuerst bemerkt."
  },
  {
    bereich: "Geschichtenideen",
    nummer: 18,
    titel: "Ein Bild wird lebendig",
    auftrag: "Schreibe eine Fantasiegeschichte.",
    fragen: ["Was ist auf dem Bild?", "Wer spricht zuerst?", "Was passiert im Zimmer?"],
    satzanfaenge: ["An der Wand hängt ein Bild.", "Plötzlich bewegt sich ...", "Dann sagt ..."],
    worthelfer: ["Bild", "sprechen", "lebendig", "Zimmer", "staunen"],
    schreibtipps: ["Schreibe fantasievoll.", "Beschreibe das Bild.", "Schreibe eine Überraschung."],
    toniTipp: "Lass etwas Unmögliches passieren."
  },
  {
    bereich: "Geschichtenideen",
    nummer: 19,
    titel: "Toni findet eine Krone",
    auftrag: "Schreibe eine Königsgeschichte.",
    fragen: ["Wem gehört die Krone?", "Wird Toni König?", "Was entscheidet er?"],
    satzanfaenge: ["Toni findet eine Krone.", "Sie gehört ...", "Toni entscheidet ..."],
    worthelfer: ["Krone", "König", "finden", "entscheiden", "Schloss"],
    schreibtipps: ["Schreibe wie in einem Märchen.", "Benutze ein Schlosswort.", "Schreibe ein gutes Ende."],
    toniTipp: "Märchen dürfen besonders klingen."
  },
  {
    bereich: "Geschichtenideen",
    nummer: 20,
    titel: "Der Regenbogen endet im Garten",
    auftrag: "Schreibe eine Regenbogengeschichte.",
    fragen: ["Was liegt dort?", "Wer wartet dort?", "Was nimmt Toni mit?"],
    satzanfaenge: ["Der Regenbogen endet ...", "Im Garten sieht Toni ...", "Am Ende ..."],
    worthelfer: ["Regenbogen", "Garten", "Farbe", "finden", "freuen"],
    schreibtipps: ["Schreibe farbig und freundlich.", "Nutze Adjektive.", "Male den Regenbogen."],
    toniTipp: "Adjektive machen dein Bild im Kopf genauer."
  },
  {
    bereich: "Starke Schreiber",
    nummer: 1,
    titel: "Anfang, Problem und Lösung",
    auftrag: "Schreibe eine Geschichte mit klarem Aufbau.",
    fragen: ["Wer ist die Hauptfigur?", "Was ist das Problem?", "Wie wird es gelöst?"],
    satzanfaenge: ["Am Anfang ...", "Doch dann ...", "Zum Schluss ..."],
    worthelfer: ["Problem", "Lösung", "plötzlich", "helfen", "schaffen"],
    schreibtipps: ["Schreibe zuerst den Anfang.", "Danach kommt das Problem.", "Am Ende wird es gelöst."],
    toniTipp: "Eine gute Geschichte braucht einen Plan."
  },
  {
    bereich: "Starke Schreiber",
    nummer: 2,
    titel: "Drei Orte",
    auftrag: "Schreibe eine Geschichte mit drei Orten.",
    fragen: ["Welche Orte kommen vor?", "Warum wechselt der Ort?", "Wo endet die Geschichte?"],
    satzanfaenge: ["Zuerst ist Toni ...", "Danach geht er ...", "Am Ende landet er ..."],
    worthelfer: ["Schule", "Wald", "Garten", "Strand", "Zuhause"],
    schreibtipps: ["Schreibe die Orte in der richtigen Reihenfolge.", "Nutze zuerst, danach, am Ende.", "Male eine kleine Karte."],
    toniTipp: "Orte helfen dir beim Erzählen."
  },
  {
    bereich: "Starke Schreiber",
    nummer: 3,
    titel: "Wörtliche Rede",
    auftrag: "Schreibe eine Geschichte, in der jemand spricht.",
    fragen: ["Wer spricht?", "Was sagt die Figur?", "Wie antwortet Toni?"],
    satzanfaenge: ["Toni sagt: ...", "Der Hund ruft: ...", "Dann fragt ..."],
    worthelfer: ["sagen", "fragen", "antworten", "rufen", "sprechen"],
    schreibtipps: ["Du kannst schreiben: Toni sagt: ...", "Setze einen Punkt am Ende.", "Lies die Sätze laut vor."],
    toniTipp: "Gespräche machen Geschichten lebendig."
  },
  {
    bereich: "Starke Schreiber",
    nummer: 4,
    titel: "Besonders spannend",
    auftrag: "Schreibe eine spannende Geschichte.",
    fragen: ["Was passiert plötzlich?", "Wer bekommt Angst?", "Wie geht es weiter?"],
    satzanfaenge: ["Plötzlich ...", "Auf einmal ...", "Ganz leise ..."],
    worthelfer: ["Angst", "dunkel", "hören", "schleichen", "mutig"],
    schreibtipps: ["Beginne mit einem spannenden Satz.", "Verrate nicht sofort alles.", "Schreibe, was Toni hört oder sieht."],
    toniTipp: "Spannung entsteht langsam."
  },
  {
    bereich: "Starke Schreiber",
    nummer: 5,
    titel: "Besonders lustig",
    auftrag: "Schreibe eine lustige Geschichte.",
    fragen: ["Was ist verrückt?", "Wer lacht?", "Wie endet der Spaß?"],
    satzanfaenge: ["Heute passiert etwas Lustiges.", "Plötzlich ...", "Alle lachen, weil ..."],
    worthelfer: ["lustig", "lachen", "verrückt", "Quatsch", "Spaß"],
    schreibtipps: ["Erfinde etwas Ungewöhnliches.", "Schreibe, warum es lustig ist.", "Lies deinen Text vor."],
    toniTipp: "Lustige Texte dürfen Quatsch enthalten."
  },
  {
    bereich: "Starke Schreiber",
    nummer: 6,
    titel: "Fortsetzung",
    auftrag: "Schreibe eine Geschichte weiter.",
    fragen: ["Was ist vorher passiert?", "Was passiert jetzt?", "Wie geht es danach weiter?"],
    satzanfaenge: ["Danach ...", "Nun ...", "Später ..."],
    worthelfer: ["weiter", "danach", "plötzlich", "gehen", "finden"],
    schreibtipps: ["Lies den Anfang noch einmal.", "Schreibe passend weiter.", "Erfinde ein Ende."],
    toniTipp: "Eine Fortsetzung muss zum Anfang passen."
  },
  {
    bereich: "Starke Schreiber",
    nummer: 7,
    titel: "Aus Tonis Sicht",
    auftrag: "Schreibe, als wärst du Toni.",
    fragen: ["Was siehst du?", "Was denkst du?", "Was fühlst du?"],
    satzanfaenge: ["Ich sehe ...", "Ich denke ...", "Ich fühle mich ..."],
    worthelfer: ["ich", "sehen", "denken", "fühlen", "froh"],
    schreibtipps: ["Schreibe in der Ich-Form.", "Nutze Gefühlswörter.", "Lies deinen Text als Toni vor."],
    toniTipp: "So klingt dein Text persönlicher."
  },
  {
    bereich: "Starke Schreiber",
    nummer: 8,
    titel: "Aus Sicht eines Tieres",
    auftrag: "Schreibe aus der Sicht eines Tieres.",
    fragen: ["Welches Tier erzählt?", "Was erlebt es?", "Was versteht es anders?"],
    satzanfaenge: ["Ich bin ein ...", "Ich sehe ...", "Die Menschen ..."],
    worthelfer: ["Tier", "laufen", "fressen", "hören", "sehen"],
    schreibtipps: ["Schreibe in der Ich-Form.", "Überlege, was das Tier kann.", "Nutze Tierwörter."],
    toniTipp: "Tiere sehen die Welt anders."
  },
  {
    bereich: "Starke Schreiber",
    nummer: 9,
    titel: "Geschichte ohne Ende",
    auftrag: "Schreibe eine Geschichte mit offenem Ende.",
    fragen: ["Wie beginnt sie?", "Was passiert?", "Welche Frage bleibt offen?"],
    satzanfaenge: ["Eines Tages ...", "Doch dann ...", "Was war das?"],
    worthelfer: ["geheim", "Frage", "plötzlich", "Tür", "hören"],
    schreibtipps: ["Schreibe spannend.", "Beende mit einer Frage.", "Lies dein Ende einem Kind vor."],
    toniTipp: "Ein offenes Ende macht neugierig."
  },
  {
    bereich: "Starke Schreiber",
    nummer: 10,
    titel: "Ein Rätsel",
    auftrag: "Schreibe ein Rätsel.",
    fragen: ["Was beschreibst du?", "Welche Hinweise gibst du?", "Wer kann es erraten?"],
    satzanfaenge: ["Ich denke an ...", "Es ist ...", "Es kann ..."],
    worthelfer: ["groß", "klein", "rund", "schnell", "Tier"],
    schreibtipps: ["Verrate das Wort nicht sofort.", "Gib drei Hinweise.", "Schreibe die Lösung auf die Rückseite."],
    toniTipp: "Ein Rätsel braucht gute Hinweise."
  },
  {
    bereich: "Starke Schreiber",
    nummer: 11,
    titel: "Ein Brief",
    auftrag: "Schreibe einen Brief.",
    fragen: ["An wen schreibst du?", "Was möchtest du erzählen?", "Welche Frage stellst du?"],
    satzanfaenge: ["Liebe ...", "Lieber ...", "Ich möchte dir erzählen ..."],
    worthelfer: ["Brief", "schreiben", "fragen", "erzählen", "freuen"],
    schreibtipps: ["Beginne mit Liebe oder Lieber.", "Schreibe eine Frage.", "Beende freundlich."],
    toniTipp: "Ein Brief ist für jemanden bestimmt."
  },
  {
    bereich: "Starke Schreiber",
    nummer: 12,
    titel: "Eine Einladung",
    auftrag: "Schreibe eine Einladung.",
    fragen: ["Wozu lädst du ein?", "Wann ist es?", "Was sollen die Gäste mitbringen?"],
    satzanfaenge: ["Ich lade dich ein ...", "Die Feier ist ...", "Bitte bring ..."],
    worthelfer: ["Einladung", "Geburtstag", "kommen", "feiern", "mitbringen"],
    schreibtipps: ["Schreibe genau, wann es ist.", "Schreibe, wo es ist.", "Vergiss den Namen nicht."],
    toniTipp: "Eine Einladung muss wichtige Infos enthalten."
  },
  {
    bereich: "Starke Schreiber",
    nummer: 13,
    titel: "Eine Anleitung",
    auftrag: "Schreibe eine kurze Anleitung.",
    fragen: ["Was erklärst du?", "Was braucht man?", "Was macht man zuerst?"],
    satzanfaenge: ["Du brauchst ...", "Zuerst ...", "Dann ..."],
    worthelfer: ["zuerst", "dann", "nehmen", "machen", "fertig"],
    schreibtipps: ["Schreibe Schritt für Schritt.", "Nutze zuerst und dann.", "Schreibe kurz und klar."],
    toniTipp: "Eine Anleitung muss man gut verstehen."
  },
  {
    bereich: "Starke Schreiber",
    nummer: 14,
    titel: "Eine Tierbeschreibung",
    auftrag: "Beschreibe ein Tier.",
    fragen: ["Wie sieht das Tier aus?", "Wo lebt es?", "Was kann es gut?"],
    satzanfaenge: ["Das Tier heißt ...", "Es hat ...", "Es lebt ..."],
    worthelfer: ["Tier", "Fell", "groß", "klein", "schnell"],
    schreibtipps: ["Benutze Adjektive.", "Suche das Tier im Wörterbuch.", "Schreibe mindestens fünf Sätze."],
    toniTipp: "Beschreiben heißt genau hinschauen."
  },
  {
    bereich: "Starke Schreiber",
    nummer: 15,
    titel: "Fünf Adjektive",
    auftrag: "Schreibe einen Text mit fünf Adjektiven.",
    fragen: ["Welche Adjektive nutzt du?", "Wird dein Text genauer?", "Kann man sich alles besser vorstellen?"],
    satzanfaenge: ["Der ...", "Die ...", "Das ..."],
    worthelfer: ["schön", "groß", "klein", "bunt", "schnell"],
    schreibtipps: ["Markiere deine Adjektive.", "Lies den Text noch einmal.", "Prüfe, ob die Wörter passen."],
    toniTipp: "Adjektive machen deinen Text genauer."
  },
  {
    bereich: "Starke Schreiber",
    nummer: 16,
    titel: "Fünf Verben",
    auftrag: "Schreibe einen Text mit fünf Verben.",
    fragen: ["Was machen die Figuren?", "Welche Verben passen?", "Wird dein Text lebendig?"],
    satzanfaenge: ["Toni ...", "Dann ...", "Danach ..."],
    worthelfer: ["laufen", "springen", "lachen", "suchen", "finden"],
    schreibtipps: ["Markiere deine Verben.", "Schreibe lebendige Sätze.", "Kontrolliere ein Verb im Wörterbuch."],
    toniTipp: "Verben zeigen, was passiert."
  },
  {
    bereich: "Starke Schreiber",
    nummer: 17,
    titel: "Ein langer Satz und zwei kurze Sätze",
    auftrag: "Schreibe einen langen Satz und zwei kurze Sätze.",
    fragen: ["Was steht im langen Satz?", "Wo passen kurze Sätze besser?", "Klingt dein Text gut?"],
    satzanfaenge: ["Toni geht ...", "Plötzlich ...", "Dann ..."],
    worthelfer: ["und", "weil", "dann", "plötzlich", "leise"],
    schreibtipps: ["Lies deinen Text laut.", "Kurze Sätze machen Spannung.", "Ein langer Satz kann viel erzählen."],
    toniTipp: "Abwechslung macht deinen Text schön."
  },
  {
    bereich: "Starke Schreiber",
    nummer: 18,
    titel: "Überraschung",
    auftrag: "Schreibe eine Geschichte mit Überraschung.",
    fragen: ["Was erwartet man zuerst?", "Was passiert anders?", "Wie reagieren die Figuren?"],
    satzanfaenge: ["Zuerst sieht alles normal aus.", "Doch plötzlich ...", "Niemand glaubt ..."],
    worthelfer: ["Überraschung", "plötzlich", "staunen", "anders", "lachen"],
    schreibtipps: ["Führe die Leser in die Irre.", "Zeige die Überraschung am Ende.", "Lies deinen Schluss noch einmal."],
    toniTipp: "Eine Überraschung macht Spaß."
  },
  {
    bereich: "Starke Schreiber",
    nummer: 19,
    titel: "Geschichte mit Gefühl",
    auftrag: "Schreibe eine Geschichte mit Gefühl.",
    fragen: ["Wer ist froh, traurig oder mutig?", "Warum?", "Was verändert sich?"],
    satzanfaenge: ["Toni fühlt sich ...", "Er ist traurig, weil ...", "Am Ende ..."],
    worthelfer: ["froh", "traurig", "mutig", "Angst", "Freude"],
    schreibtipps: ["Nutze Gefühlswörter.", "Schreibe, warum die Figur so fühlt.", "Kontrolliere ein Gefühlswort."],
    toniTipp: "Gefühle machen Geschichten echt."
  },
  {
    bereich: "Starke Schreiber",
    nummer: 20,
    titel: "Text überarbeiten",
    auftrag: "Überarbeite deinen Text wie ein Profi.",
    fragen: ["Fehlen Punkte?", "Sind Satzanfänge groß?", "Hast du Wörter im Wörterbuch geprüft?"],
    satzanfaenge: ["Ich prüfe ...", "Ich verbessere ...", "Jetzt ist mein Text ..."],
    worthelfer: ["prüfen", "verbessern", "lesen", "Punkt", "Wort"],
    schreibtipps: ["Lies deinen Text langsam.", "Verbessere mindestens ein Wort.", "Kontrolliere Satzanfänge und Punkte."],
    toniTipp: "Gute Schreiber verbessern ihre Texte."
  }
];
